spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?serverTimezone=Asia/Shanghai&useSSL=false
    username: wiki
    password: wiki
  application:
    name: wiki
  redis:
    host: 139.159.142.252
    port: 6379
server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
